apiVersion: 'doppler.com/v1'
kind: DopplerSecret
metadata:
  name: my-app-secret
  namespace: default
spec:
  serviceToken: '$SERVICE_TOKEN' # This will be replaced by envsubst so it's never hard-coded and saved to the file system
  secretName: doppler-app-secret # Name of the secret the controller will create