apiVersion: doppler.com/v1
kind: DopplerSecret
metadata:
  name: dopplersecret-test
spec:
  serviceToken: $DOPPLER_TOKEN  # Change to your Doppler Service Token
  secretName: doppler-test-secret # Kubernetes Secret name
