---
apiVersion: 'k8s.dashlabs.ai/v1'
kind: DopplerSecret
metadata:
  name: alpine-secret
  namespace: default
spec:
  dopplerAPIKey: 'DOPPLER_API_KEY'
  secretName: testing-secret
  updateDeployments:
    - alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: alpine
        image: alpine
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        envFrom:
            - secretRef:
                name: testing-secret
        resources: {}
